### ISSUE TITLE
Basic usage discussion

### ISSUE THREAD

**Issue by drgomesp** [Respect/ValidationBundle#1]
This issue is aimed to allow us to discuss the basic usage of Respect\Validation rules inside of a Symfony application using the ValidationBundle.

As previously discussed in [#112](https://github.com/Respect/Validation/issues/112), we are probably going to need a Metadata class to delegate the validation calls to the right validation rules.

We could create this Metadata class as a Symfony [custom constraint](http://symfony.com/doc/master/cookbook/validation/custom_constraint.html) simple class.

I'm not sure how, but the usage would be something like this:

``` php
class User
{
    /**
     * @Respect\Validation\NotEmpty
     * @Respect\Validation\Between{min="6", max="24"}
     */
    protected $password;
}
```

Or we can talk about what @alganet proposed, which is a more complex integration using the power of Symfony's DI component to inject validators as services bind rules to class properties.

It would be something like this:

``` yaml
# app/config/config.yml
services:
    validator.user.password:
        class: Respect\Validation\Validator
        calls: 
            - [string]
            - [alnum, [_]]
            - [length, [6,24]]
```

And bind the created rules using a _Bind_ annotation: 

``` php
/**
 * NOT SURE WHAT TO IMPORT HERE
 */
class User
{
    /**
     * @Respect\ValidationBundle\Bind(service=validator.user.password)
     */
    protected $password;
}
```

Let there be discussion.
